### ISSUE TITLE
Multiple copies of React loaded when using React Toolbox

### ISSUE THREAD

**Issue by laucheukhim** [thereactivestack/kickstart-meteor-react-router#83]
I run into the following error when using this with [React Toolbox](https://github.com/react-toolbox/react-toolbox):

> invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Here is a [repository I forked](https://github.com/laucheukhim/kickstart-meteor-react-router-with-react-toolbox) to demonstrate the bug. It is possibly related to #82.

**Comment by laucheukhim** [comment]
It turns out the problem lies in [ReactRouterSSR](https://github.com/thereactivestack/meteor-react-router-ssr).

A different copy of React is loaded when ReactDOM is imported in [meteor-react-router-ssr/lib/client.jsx](https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/client.jsx#L2). Node exhibits some [special behavior](http://stackoverflow.com/a/26703392) when it comes to loading modules that belong to different npm modules. The ReactDOM imported in ReactRouterSSR is a different instance from the one imported in the project code, because they are two different modules.

To workaround this, I modified ReactRouterSSR to supply my instance of ReactDOM for rendering.

Download [ReactRouterSSR](https://github.com/thereactivestack/meteor-react-router-ssr) and put it under the [`packages/` directory](http://guide.meteor.com/writing-atmosphere-packages.html#overriding-atmosphere-packages) at the root of your Meteor app, and change [this line](https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/client.jsx#L60)

```javascript
ReactDOM.render(app, rootElement);
```

to

```javascript
(clientOptions.ReactDOM || ReactDOM).render(app, rootElement);
```

Then in your project files, pass your instance of ReactDom to ReactRouterSSR as a client option.

```javascript
import { ReactRouterSSR } from 'meteor/reactrouter:react-router-ssr';
import ReactDOM from 'react-dom';
import routes from 'path/to/routes';

const clientOptions = { ... , ReactDOM };
const serverOptions = { ... };
ReactRouterSSR.Run(routes, clientOptions, serverOptions);
```

Now you can use React Toolbox or whatever library out there without running into this error.

**Comment by guilhermedecampo** [comment]
Thanks man! Wish I could see this before! Tons of time to understand what was going on!

own you a beer @laucheukhim =)

**Comment by mxs** [comment]
@laucheukhim thanks a million! 🙏  You have saved me so much time on this issue.

Pardon my shallow understanding of Meteor packages but this seems like fix is required in ReactRouterSSR where the dependency on ReactDOM is a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) ?

**Comment by SachaG** [comment]
Thanks so much @laucheukhim!

**Comment by xue2han** [comment]
Having struggled with it for a long time,I think I have gotten the reason behind it:
when you use meteor-react-router-ssr with webpack:react,Webpack will pack React for your code,while meteor’s module system required by meteor-react-router-ssr  will pack React for meteor-react-router-ssr.So there will be two copies of React.That is the problem.

[this solution](https://github.com/thereactivestack/kickstart-meteor-react-router/issues/83#issuecomment-224975331) does works,since it just passes React packed by Webpack to meteor-react-router-ssr. But it is not a very good hack,you have to do it again if you want to require another Atmosphere package which requires React.so I am wondering if we can totally solve the problem.

**Comment by SachaG** [comment]
So would this work better if meteor-react-router-ssr was itself an NPM package instead of a Meteor package?

**Comment by veeramarni** [comment]
I'm in same boat trying to figure out best way to prevent react duplication, i have modified webpack:react's webpack.config.js to use peerDependencies for react and react-dom instead of direct dependencies, but that didn't get me anywhere.

**Comment by xue2han** [comment]
@SachaG yes.It should work.

**Comment by xue2han** [comment]
@veeramarni  It won’t work,since Webpack won’t pack React for your code, and your code can not get access to React packed by meteor’s modules system.

**Comment by eXon** [comment]
I'm closing this issue because it is not in the proper git repo. Not sure what to fix on react-router-ssr to make sure no copy is made.

**Comment by veeramarni** [comment]
@eXon I have created a sample repo to replicate the issue [here](https://github.com/veeramarni/kickstart-meteor-react-router)

I have identified that when we use `react` or any dependencies using `check-npm-versions` the libs are loaded into `modules.js` which by nature meteor generates it. Thus, we will have two copies of react one in `modules.js` and webpack loaded file `React.js` during build. Because of two copies  of React we get intermittent issues when using third party react component such as react-bootstrap from npm package. Please let me know if you need more details.

**Comment by veeramarni** [comment]
@SachaG  Do you find workaround for this? I have opened issue with meteor as well.

https://github.com/meteor/meteor/issues/7651

**Comment by veeramarni** [comment]
@xue2han then is there way  to prevent `react.js` from bundling into `meteor`

**Comment by john-osullivan** [comment]
@eXon , I think the fix would go in `meteor:webpack` to have Meteor packages load their dependencies from webpack if they're available.  Alternately, a smaller fix would be to add the `react-router-ssr` patch the other commenters pointed out.
